apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    app-version: "V1.00.00"
    project: "Green-House"
  name: ghp-frontend-service
  namespace: greenhouse
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ghp-frontend-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ghp-frontend-service
    spec:
      containers:
        - name: ghp-frontend-service
          image: asia-south1-docker.pkg.dev/true-solstice-453217-f5/green-house-repository/ghp-frontend-service:V1.00.00.01
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9191
              protocol: TCP
          resources:
            requests:
              memory: "250Mi"
              cpu: "100m"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: TZ
              value: "Asia/Colombo"
      imagePullSecrets:
        - name: gcr-secret
      dnsPolicy: ClusterFirst
      hostNetwork: false
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 120
